development:
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: postcrossing

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/0
  channel_prefix: postcrossing
